# Copyright 2020-present Ciena Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: "v1"
name: "bbsim-sadis-server"
version: "1.0.2"
description: "A Helm chart for Voltha's BBSIM SADIS Server"
keywords:
  - "onf"
  - "voltha"
  - "bbsim"
  - "sadis"
home: "https://www.opennetworking.org/voltha"
icon: "https://guide.opencord.org/logos/voltha.svg"
sources:
  - "https://github.com/ciena/bbsim-sadis-server"
maintainers:
  - name: "Ciena Corporation"
    email: "info@ciena.com"
    url: "https://www.ciena.com"

appVersion: "1.2"
